name: CI Pipeline

on:
    push:
      branches:
        - master

jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
            - name: Add SSH key
              uses: webfactory/ssh-agent@v0.5.3 
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: Test connect
              run: |
                ssh -o StrictHostKeyChecking=no ompuser@hseomp.ru << EOF
                    echo "Hello world" > test.txt
                    ls -la
                EOF
